name: Build and Publish to Dockerhub

on:
  pull_request:
    types:
     - opened
    branches:
     - main
  workflow_dispatch:

env:
  CONTAINER_NAME: "anusha-repo"
  RESOURCE_GROUP: "growth_group"
  CLUSTER_NAME: "growthfarm"
  DEPLOYMENT_MANIFEST_PATH: "k8s/deployment.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with brnach and tag
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build with Docker
        run: |
            docker build -f Dockerfile . -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ github.sha }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.CONTAINER_NAME }}:latest
      - name: Push
        run: |
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
            echo $GITHUB_SHA
